### ISSUE TITLE
failed update / check for internet connection launches app twice

### ISSUE THREAD

**Issue by zoulztealer** [madbomb122/BlackViperScript#27] opened 2018-09-03 15:34 UTC
**Describe the bug**
dont know where its coming from, but this happend also yesterday with the other bug when checking for updates.

when i clicked on run script today (check for updates enabled on run), there was something in the console, guess it was the status message for checking and downloading updates.

after that the console was cleared and the app launched a second time / restarted without closing the old instance first.

the old instance window is locked and cant be moved or closed, too.

when the script is ran from the new instance, there is no output in the console window, only inside the app under tab service changes.

**To Reproduce**
1. click on run script and have check for updates on run enabled
2. observe console window / app behaviour for restarting / not closing the old instance first.

**Expected behavior**
old instance should be closed on / after update.

**Screenshots**
![bvscript7](https://user-images.githubusercontent.com/42149920/44994513-3c3b9a00-af9f-11e8-9a35-4b7fc867b726.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Creator's Update]
 - OS Build: [e.g. Home]
 - Modded OS: [e.g. No] -If you are using an OS that has removed items using a program like Nlite

**Additional context**
 - Script Version: 5.2.3 (sep 01 2018) to 5.2.4
 - Release Type: 4.0 (may 29 2018)

**Comment by madbomb122** [comment] 2018-09-03 16:04
There is a console message about if an update was found or not, when it check for an update. 
I will change it so it keeps the message on there instead of clearing the console.

The old app not closing is a bug i fixed in 5.2.4, I fix it while fixing the other update issue...

The old app can be closed using task manager or by right-click on task bar item for it and saying close. 

The Console being blank might be from the Old script (the updated script launches a new window, i can't tell the script to use the window already being used). 

But i'll check on the blank console after an update.

**Comment by madbomb122** [comment] 2018-09-03 16:06
BTW, make sure to give your comment on the Issue/Suggestion I have open.

**Comment by madbomb122** [comment] 2018-09-05 19:37
Accidentally disabled the script updating when I posted v5.2.4.

**Comment by madbomb122** [comment] 2018-09-05 19:38
Once I test a few things I will post the new updated script with the new features

**Comment by zoulztealer** [comment] 2018-09-13 18:25
> Once I test a few things I will post the new updated script with the new features

hey man, not sure if we had this already and you left this out on purpose, but can you make the changes on the switches "all - change all services" and "min -change services" under tab "services options" -> black viper configuration options (bv services only) permanent? i have to set to "all" manually, everytime i launch it. would be really cool, thx.

**Comment by madbomb122** [comment] 2018-09-13 18:34
that is odd, it keeps the setting for me, i'll take a look into it

**Comment by madbomb122** [comment] 2018-09-13 18:39
did some checking, it keeps the setting saved..
wonder if it was a bug that i fixed while doing other improvements

**Comment by zoulztealer** [comment] 2018-09-14 14:58
> did some checking, it keeps the setting saved..
> wonder if it was a bug that i fixed while doing other improvements

ye, thought so. for me, its not saving. 🤐

**Comment by madbomb122** [comment] 2018-09-14 18:19
how are you running the script?
if you are running it using the bat file.. that is the cause.
(edit the bat file and change `Set All_or_Min=min` to `Set All_or_Min=all` )

I will be doing an update for everything. So you will want to download from the repo using the download link.

If all goes well i will have the updates uploaded within the next day.

**Comment by madbomb122** [comment] 2018-09-15 00:48
script has been updated.. all issues listed here should be fixed by downloading new release [here](https://github.com/madbomb122/BlackViperScript/releases)

If issue still persists please let me know, thanks

**Closed as completed** 2018-09-15 00:49 UTC
